version: '2'
services:
  db:
    image: postgres:9.6
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - settings.env
    environment:
      - "POSTGRES_DB=open-dccon-selector"
      - "POSTGRES_USER=ods"
      - "LC_COLLATE=C"

  flask:
    build: ./backend
    links:
      - db
    expose:
      - "8088"
    command: python3 debug.py
    tty: true
    env_file:
      - settings.env
    volumes:
      - ./backend/flask:/var/www/flask
      - ./backend/flask.conf:/etc/nginx/sites-available/flask.conf:ro
      - ./backend/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./frontend/dist/static:/var/www/flask/app/static:ro
      - ./frontend/dist/index.html:/var/www/flask/app/templates/index.html:ro
      - ./frontend/dist/sammi-color.manifest:/var/www/flask/app/templates/sammi-color.manifest:ro
      - ./log/uwsgi:/var/log/uwsgi
      - ./log/nginx:/var/log/nginx
    restart: unless-stopped

  web:
    build: ./frontend
    expose:
      - "8080"
    env_file:
      - settings.env
    volumes:
     - ./frontend:/frontend
     - node-modules:/frontend/node_modules

volumes:
  node-modules:
