version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - settings.env
    environment:
      - "POSTGRES_DB=open-dccon-selector"
      - "POSTGRES_USER=ods"
      - "LC_COLLATE=C"

  flask:
    build: ./backend
    links:
      - db
#    expose:
#      - "8088"
    ports:
      - "8088:8088"
    command: python3 debug.py
    tty: true
    env_file:
      - settings.env
    volumes:
      - ./backend/flask:/var/www/flask
      - ./backend/localhost-ssl.crt:/etc/ssl/private/localhost-ssl.crt:ro
      - ./backend/localhost-ssl.key:/etc/ssl/private/localhost-ssl.key:ro
      - ./backend/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./frontend/dist:/frontend/dist:ro
      - ./log/uwsgi:/var/log/uwsgi
      - ./log/nginx:/var/log/nginx
    restart: unless-stopped

volumes:
  db-data:
